require_relative "../lib/models/the_fridge.rb"

TheFridge.create( item_name: "Organic Valley", category: "milk", quantity: 2 )
TheFridge.create( item_name: "Lucerne", category: "butter", quantity: 1 )
TheFridge.create( item_name: "Land O Lakes", category: "butter", quantity: 1 )
TheFridge.create( item_name: "GT's Synergy", category: "kombucha", quantity: 7 )
TheFridge.create( item_name: "Pepsi", category: "soda", quantity: 2 )
TheFridge.create( item_name: "Driscolls - raspberry", category: "fruit", quantity: 2 )
TheFridge.create( item_name: "Driscolls - blueberry", category: "fruit", quantity: 2 )
TheFridge.create( item_name: "Voskos Honey", category: "yogurt", quantity: 5 )
TheFridge.create( item_name: "Stonyfield", category: "yogurt", quantity: 5 )
TheFridge.create( item_name: "Brie de Meaux", category: "cheese", quantity: 1 )
TheFridge.create( item_name: "Bleu d'Auvergne", category: "cheese", quantity: 2 )
TheFridge.create( item_name: "Ayinger", category: "beer", quantity: 11 )
TheFridge.create( item_name: "Maille", category: "mustard", quantity: 1 )